### PR TITLE
Add Process Priority setting

### PR DESCRIPTION
**Pull request by Froghut**
Add a setting to the plugin configuration to change the Process Priority of the ffmpeg .bif generation process

### CODE REVIEW

**Comment by nicknsy** [comment]
Thanks for the pull request. Could you explain the use of setting process priority? I don't really know what it does so in what cases would it be useful to set and change?

**Comment by Froghut** [comment]
So if 100% of cpu power is used the process priority will determine how much of the cpu power the processes will get. So if you set priority to idle the process might get nothing, and if you set it to High it will get most of the requested cpu power.
On my server for example I'm sometimes close to utilizing my CPU 100% and I don't care that much if .bif generation gets slower during those times, I'd rather my other process get priority.

**Comment by satmandu** [comment]
Exactly this. Right now bif generation on my server is at normal priority. But I should be able to set it to lowest priority, as there are other things (like playing videos) that should take higher priority.

**Comment by nicknsy** [comment]
I've never really done git merges/pulls before so I'm not sure if I can do this myself, but could you change this to be a pull request to the beta branch?

**Comment by Froghut** [comment]
Haven't worked with git/github that much before myself, but I think I managed to change it to the beta branch :)

**Pull request merged**
